In [5]:
#importing libraries

In [70]:
import pandas as pd
import numpy as np

In [71]:
# importing dataset

In [72]:
db = pd.read_excel("C:/Users/vaish/OneDrive/Desktop/datasets and projects/Datasets/Google ads hourly analysis 20th june.xlsx")

In [73]:
db

Sr no  Impressions   Clicks  Cost      CTR        CPC  Cold_Leads   \
0   00:00:00          9241     554    577  0.0600   1.041516           22   
1   00:30:00          8873     355    498  0.0400   1.402817           14   
2   01:00:00          3956     119    396  0.0300   3.327731            5   
3   01:30:00           956      38     95  0.0400   2.500000            2   
4   02:00:00           548      11     41  0.0200   3.727273            0   
5   02:30:00            62       1     23  0.0200  23.000000            0   
6   03:00:00            48       1     15  0.0200  15.000000            0   
7   03:30:00            36       0      9  0.0120        NaN            0   
8   04:00:00            19       0      7  0.0110        NaN            0   
9   04:30:00            26       0      6  0.0190        NaN            0   
10  05:00:00            45       1      7  0.0140   7.000000            0   
11  05:30:00            59       1     12  0.0200  12.000000            0   
12  06:00:00            36       0      9  0.0020        NaN            0   
13  06:30:00           263       5     14  0.0200   2.800000            0   
14  07:00:00           413       9     18  0.0220   2.000000            0   
15  07:30:00           368      18     36  0.0500   2.000000            1   
16  08:00:00           565      34     49  0.0600   1.441176            1   
17  08:30:00           486      34     63  0.0700   1.852941            1   
18  09:00:00           656      59     81  0.0900   1.372881            2   
19  09:30:00          1025     123    148  0.1200   1.203252            5   
20  10:00:00          1475     192    212  0.1300   1.104167            8   
21  10:30:00          1488      85    180  0.0569   2.117647            3   
22  11:00:00          1965     295    241  0.1500   0.816949           12   
23  11:30:00          2644     317    345  0.1200   1.088328           13   
24  12:00:00          3248     422    256  0.1300   0.606635           17   
25  12:30:00          3965     476    267  0.1200   0.560924           19   
26  13:00:00          4159     582    295  0.1400   0.506873           23   
27  13:30:00          4859     680    286  0.1400   0.420588           27   
28  14:00:00          4723     614    287  0.1300   0.467427           25   
29  14:30:00          5012     702    289  0.1400   0.411681           28   
30  15:00:00          5656     792    287  0.1400   0.362374           32   
31  15:30:00          5648     791    361  0.1400   0.456384           32   
32  16:00:00          4999     700    480  0.1400   0.685714           28   
33  16:30:00          4125    1031    399  0.2500   0.387003           41   
34  17:00:00          5948     952    509  0.1600   0.534664           38   
35  17:30:00          9458    1797    652  0.1900   0.362827           72   
36  18:00:00          9512    1998    641  0.2100   0.320821           80   
37  18:30:00          9477    2180    704  0.2300   0.322936           87   
38  19:00:00          9888    2571    655  0.2600   0.254765          103   
39  19:30:00         10256    2154    945  0.2100   0.438719           86   
40  20:00:00          9489    1423    628  0.1500   0.441321           57   
41  20:30:00          9899    1386    647  0.1400   0.466811           55   
42  21:00:00          9659    1545    632  0.1600   0.409061           62   
43  21:30:00          7845    1177    647  0.1500   0.549703           47   
44  22:00:00          7444    1191    625  0.1600   0.524769           48   
45  22:30:00          8401    1596    947  0.1900   0.593358           64   
46  23:00:00          8955    1522    948  0.1700   0.622865           61   
47  23:30:00          9120    1459    936  0.1600   0.641535           58   

    Warm Leads  Hot Leads  
0           11          2  
1            7          1  
2            3          1  
3            1          0  
4            0          0  
5            0          0  
6            0          0  
7        

In [74]:
#checking null values

In [75]:
db.isnull().sum()

Sr no           0
Impressions     0
Clicks          0
Cost            0
CTR             0
CPC             4
Cold_Leads      0
Warm Leads      0
Hot Leads       0
dtype: int64

In [76]:
# filling the null values

In [77]:
v=db.fillna(db.mean())

C:\Users\vaish\AppData\Local\Temp\ipykernel_32608\834238472.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  v=db.fillna(db.mean())


In [78]:
v.isnull().sum()

Sr no           0
Impressions     0
Clicks          0
Cost            0
CTR             0
CPC             0
Cold_Leads      0
Warm Leads      0
Hot Leads       0
dtype: int64

In [79]:
# data preprocessing

In [80]:
file=v.drop(["Sr no","CTR","CPC","Warm Leads"], axis = 1)

In [81]:
file

Impressions   Clicks  Cost   Cold_Leads   Hot Leads
0           9241     554    577           22          2
1           8873     355    498           14          1
2           3956     119    396            5          1
3            956      38     95            2          0
4            548      11     41            0          0
5             62       1     23            0          0
6             48       1     15            0          0
7             36       0      9            0          0
8             19       0      7            0          0
9             26       0      6            0          0
10            45       1      7            0          0
11            59       1     12            0          0
12            36       0      9            0          0
13           263       5     14            0          0
14           413       9     18            0          0
15           368      18     36            1          0
16           565      34     49            1          0
17           486      34     63            1          0
18           656      59     81            2          0
19          1025     123    148            5          1
20          1475     192    212            8          1
21          1488      85    180            3          0
22          1965     295    241           12          1
23          2644     317    345           13          1
24          3248     422    256           17          2
25          3965     476    267           19          2
26          4159     582    295           23          3
27          4859     680    286           27          3
28          4723     614    287           25          3
29          5012     702    289           28          3
30          5656     792    287           32          3
31          5648     791    361           32          3
32          4999     700    480           28          3
33          4125    1031    399           41          4
34          5948     952    509           38          4
35          9458    1797    652           72          8
36          9512    1998    641           80          8
37          9477    2180    704           87          9
38          9888    2571    655          103         11
39         10256    2154    945           86          9
40          9489    1423    628           57          6
41          9899    1386    647           55          6
42          9659    1545    632           62          7
43          7845    1177    647           47          5
44          7444    1191    625           48          5
45          8401    1596    947           64          7
46          8955    1522    948           61          7
47          9120    1459    936           58          6

In [82]:
# discriptive analysis

In [83]:
file.sum()

Impressions     206998
Clicks           31993
Cost             16405
Cold_Leads        1279
Hot Leads          135
dtype: int64

In [84]:
# calculating average value

In [85]:
file.mean()

Impressions     4312.458333
Clicks           666.520833
Cost             341.770833
Cold_Leads        26.645833
Hot Leads          2.812500
dtype: float64

In [86]:
file.head()

Impressions   Clicks  Cost   Cold_Leads   Hot Leads
0          9241     554    577           22          2
1          8873     355    498           14          1
2          3956     119    396            5          1
3           956      38     95            2          0
4           548      11     41            0          0

In [105]:
x=file.iloc[:,:-1].values
y=file.iloc[:,-1].values

In [106]:
x

array([[ 9241,   554,   577,    22],
       [ 8873,   355,   498,    14],
       [ 3956,   119,   396,     5],
       [  956,    38,    95,     2],
       [  548,    11,    41,     0],
       [   62,     1,    23,     0],
       [   48,     1,    15,     0],
       [   36,     0,     9,     0],
       [   19,     0,     7,     0],
       [   26,     0,     6,     0],
       [   45,     1,     7,     0],
       [   59,     1,    12,     0],
       [   36,     0,     9,     0],
       [  263,     5,    14,     0],
       [  413,     9,    18,     0],
       [  368,    18,    36,     1],
       [  565,    34,    49,     1],
       [  486,    34,    63,     1],
       [  656,    59,    81,     2],
       [ 1025,   123,   148,     5],
       [ 1475,   192,   212,     8],
       [ 1488,    85,   180,     3],
       [ 1965,   295,   241,    12],
       [ 2644,   317,   345,    13],
       [ 3248,   422,   256,    17],
       [ 3965,   476,   267,    19],
       [ 4159,   582,   295,    23],
 

In [107]:
y

array([ 2,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  1,  1,  0,  1,  1,  2,  2,  3,  3,  3,  3,  3,  3,  3,  4,
        4,  8,  8,  9, 11,  9,  6,  6,  7,  5,  5,  7,  7,  6],
      dtype=int64)

In [108]:
# decision tree classifier

In [109]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test= train_test_split(x, y, test_size=0.20, random_state=20)

In [110]:
print(x_train)

[[ 9241   554   577    22]
 [ 3965   476   267    19]
 [  486    34    63     1]
 [  413     9    18     0]
 [ 5656   792   287    32]
 [  656    59    81     2]
 [   45     1     7     0]
 [  956    38    95     2]
 [10256  2154   945    86]
 [  263     5    14     0]
 [ 7444  1191   625    48]
 [ 3956   119   396     5]
 [ 3248   422   256    17]
 [ 9477  2180   704    87]
 [   62     1    23     0]
 [ 9899  1386   647    55]
 [ 5012   702   289    28]
 [ 7845  1177   647    47]
 [   48     1    15     0]
 [  565    34    49     1]
 [ 1025   123   148     5]
 [ 4859   680   286    27]
 [ 4125  1031   399    41]
 [ 9659  1545   632    62]
 [ 1488    85   180     3]
 [ 4999   700   480    28]
 [ 5948   952   509    38]
 [   36     0     9     0]
 [ 1965   295   241    12]
 [   59     1    12     0]
 [ 1475   192   212     8]
 [   26     0     6     0]
 [ 8955  1522   948    61]
 [ 4723   614   287    25]
 [ 5648   791   361    32]
 [  368    18    36     1]
 [ 4159   582   295    23]
 

In [111]:
print(y_train)

[2 2 0 0 3 0 0 0 9 0 5 1 2 9 0 6 3 5 0 0 1 3 4 7 0 3 4 0 1 0 1 0 7 3 3 0 3
 8]


In [125]:
print(x_test)

[[-1.2663668  -1.07139066 -1.26139794 -1.08093512]
 [-1.39264541 -1.08364149 -1.36120602 -1.08093512]
 [-0.76602659 -0.73059488 -0.36899633 -0.71969716]
 [ 0.77987188  0.54126389  1.36590287  0.53074192]
 [ 0.72091003 -0.68827384  0.08014001 -0.69190963]
 [ 0.608238    0.69384239  1.39819372  0.69746713]
 [ 0.96320264  1.77971131  0.54101848  1.781181  ]
 [-1.38858731 -1.08364149 -1.35533496 -1.08093512]
 [ 0.87344696  1.1415545   0.49992104  1.14206769]
 [ 0.86795658  0.50117027  0.46175913  0.50295439]]


In [126]:
print(y_test)

[ 0  0  1  6  1  7 11  0  8  6]


In [112]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [113]:
x_train = sc.fit_transform(x_train)

In [114]:
x_test = sc.fit_transform(x_test)

In [127]:
print(x_train)

[[ 1.53085443 -0.05027403  1.00173901 -0.05603023]
 [ 0.01663102 -0.17332293 -0.1520042  -0.17431626]
 [-0.9818495  -0.87060004 -0.91124167 -0.88403245]
 [-1.00280066 -0.91003879 -1.07872052 -0.92346112]
 [ 0.50195168  0.32518288 -0.07756915  0.33825655]
 [-0.93305914 -0.83116129 -0.84425013 -0.84460377]
 [-1.10841746 -0.92265919 -1.11965979 -0.92346112]
 [-0.84695849 -0.86428984 -0.79214559 -0.84460377]
 [ 1.82216163  2.47380601  2.37134385  2.46740511]
 [-1.04585099 -0.91634899 -1.09360753 -0.92346112]
 [ 1.01511154  0.95462534  1.18038312  0.96911538]
 [ 0.014048   -0.73650829  0.32810185 -0.72631774]
 [-0.18914953 -0.25851063 -0.19294347 -0.25317361]
 [ 1.59858694  2.51482231  1.47440155  2.50683379]
 [-1.10353842 -0.92265919 -1.06011176 -0.92346112]
 [ 1.71970185  1.26224759  1.26226167  1.24511612]
 [ 0.31712228  0.18320338 -0.07012565  0.18054184]
 [ 1.13019941  0.93253964  1.26226167  0.9296867 ]
 [-1.10755645 -0.92265919 -1.08988578 -0.92346112]
 [-0.95917633 -0.87060004 -0.96

In [129]:
print(x_test)

[[-1.2663668  -1.07139066 -1.26139794 -1.08093512]
 [-1.39264541 -1.08364149 -1.36120602 -1.08093512]
 [-0.76602659 -0.73059488 -0.36899633 -0.71969716]
 [ 0.77987188  0.54126389  1.36590287  0.53074192]
 [ 0.72091003 -0.68827384  0.08014001 -0.69190963]
 [ 0.608238    0.69384239  1.39819372  0.69746713]
 [ 0.96320264  1.77971131  0.54101848  1.781181  ]
 [-1.38858731 -1.08364149 -1.35533496 -1.08093512]
 [ 0.87344696  1.1415545   0.49992104  1.14206769]
 [ 0.86795658  0.50117027  0.46175913  0.50295439]]


In [130]:
from sklearn.tree import DecisionTreeClassifier
DT= DecisionTreeClassifier(criterion="gini", random_state=0)
DT.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [131]:
print(DT.predict(sc.transform([[8401,1596,947,64]])))

[4]


In [132]:
# Predicting the Test set results

In [133]:
y_pred = DT.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[ 0  0]
 [ 0  0]
 [ 1  1]
 [ 4  6]
 [ 1  1]
 [ 4  7]
 [ 8 11]
 [ 0  0]
 [ 6  8]
 [ 4  6]]


In [134]:
# making the confusion matrix

In [135]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0]]


0.5